-- =====================================================================
-- Ridwane — le modèle de rôles
-- =====================================================================
-- APPLIQUÉ en base le 2026-08-02. Ce fichier porte le raisonnement ;
-- `schema.sql` porte l'état.

-- ---------------------------------------------------------------------
-- TÂCHE 1 — LE PROMOTEUR EN LECTURE SEULE
-- ---------------------------------------------------------------------
--
-- « admin » N'EXISTE PLUS.
--
-- C'était le propriétaire de l'école sous un autre nom. Les deux comptes
-- qui le portaient sont devenus `promoteur`, et la valeur a été retirée
-- de profiles_role_check : elle ne peut plus être attribuée.
--
-- Ce que le promoteur PERD — toute l'écriture — a été reventilé, jamais
-- supprimé. Une capacité qui n'appartient plus à personne est pire qu'un
-- droit mal placé : elle ne se voit qu'au moment où quelqu'un en a
-- besoin, et il est alors trop tard.
--
-- ---------------------------------------------------------------------
-- POURQUOI DEUX FONCTIONS JUMELLES
--
-- `is_encadrement()` et `is_direction_generale()` servaient à la fois en
-- LECTURE et en ÉCRITURE. Le promoteur doit rester dans la première et
-- disparaître de la seconde : les retirer de ces fonctions lui aurait
-- fermé la lecture, ce qui est tout le contraire du modèle.
--
-- D'où `encadrement_ecrit()` et `dg_ecrit()`, réservées aux policies
-- d'écriture. La substitution a été faite PAR BALAYAGE de pg_policies,
-- pas à la main : sur 48 policies on en oublie une, et celle qu'on
-- oublie est un trou qui ne se voit pas. Le balayage, lui, se recompte.
--
--   48 policies d'écriture .......... is_encadrement    -> encadrement_ecrit
--   12 policies d'écriture .......... is_direction_generale -> dg_ecrit
--    7 policies de lecture ........... intactes
--
-- ---------------------------------------------------------------------
-- CE QUE « admin » PORTAIT, ET OÙ C'EST PARTI
--
--   Frais supprimés ................. comptable (can_write_money)
--   Clôture de la paie .............. comptable
--   Règlement intérieur ............. directeur général (vaut pour
--                                     toute l'école ; les surveillants
--                                     le font respecter, ils ne le
--                                     rédigent pas)
--   Journal d'activité .............. promoteur, et directeur général
--                                     — lignes financières comprises
--                                     seulement si le promoteur l'y a
--                                     autorisé
--   Notes .......................... l'encadrement qui écrit, resserré
--                                     ensuite au réglage « qui note »
--   Devoirs, présence par leçon ..... doublon de l'encadrement dans la
--                                     même expression : disparaît sans
--                                     rien emporter
--
-- ---------------------------------------------------------------------
-- L'EXPLOITANT DE LA PLATEFORME — UNE TABLE, PAS UN RÔLE
--
-- `platform_operators` plutôt qu'une valeur de profiles.role. Un profil
-- appartient à une école (school_id) ; l'exploitant non. Dans la même
-- énumération, il serait devenu un « exploitant de l'école X », et
-- chaque liste `role in (...)` aurait dû penser à l'exclure — c'est
-- exactement le genre d'oubli qui ouvre un accès.
--
-- Séparé, on peut être promoteur de sa propre école ET exploitant, ce
-- qui est le cas réel aujourd'hui.
--
-- Aucune policy, délibérément — comme school_creation_grants. RLS active
-- et zéro policy ferme la table à `authenticated` : seule la clé service
-- role y accède. Lui ajouter une policy de lecture révélerait qui tient
-- la plateforme.
--
-- ---------------------------------------------------------------------
-- L'ACCÈS DU DG À LA COMPTABILITÉ — UN DRAPEAU D'ÉCOLE
--
-- `schools.dg_voit_comptabilite`, et non un second rôle. Un rôle
-- « directeur_general_avec_comptabilite » aurait doublé chaque liste
-- pour une seule différence, et changer d'avis aurait voulu dire
-- renommer le compte au lieu de basculer un interrupteur. Porté par
-- l'école, le réglage survit au remplacement du directeur général.
--
-- C'est un droit de LECTURE. `can_write_money()` ne nomme que le
-- comptable, quelle que soit la valeur du drapeau.


-- ---------------------------------------------------------------------
-- TÂCHE 2 — LES DIRECTIONS ONT UN CYCLE, LES DIRECTEURS SONT PAIRS
-- ---------------------------------------------------------------------
--
-- `directions.cycle` est une COLONNE et non une table de correspondance :
-- un cycle peut avoir plusieurs directions, mais une direction n'
-- appartient qu'à un cycle. C'est un rattachement, pas une relation à
-- deux sens. Même vocabulaire que `classes.cycle`, délibérément — deux
-- énumérations parallèles finiraient par diverger.
--
-- AUCUNE HIÉRARCHIE ENTRE DIRECTEURS. Il n'existe nulle part de test
-- « directeur A au-dessus de directeur B » : chacun est borné à sa
-- direction par `current_direction_id()`, et deux directions ne se
-- voient pas. C'est ce qui les rend pairs — non pas une règle ajoutée,
-- mais l'absence de toute règle qui les ordonnerait.
--
-- « SES » ENSEIGNANTS SE LISENT, ILS NE SE STOCKENT PAS. Un enseignant
-- n'a pas de direction en propre : il en tient une par les classes où il
-- intervient. Une colonne `teachers.direction_id` aurait dû être
-- corrigée à chaque affectation, et aurait menti dès la première
-- omission.
--
-- LE CAS QUI COMPTE : un enseignant affecté NULLE PART est visible de
-- tous les directeurs. Sans cela, celui qui vient de le créer ne
-- pourrait plus le rouvrir pour l'affecter — la fiche serait perdue
-- entre sa création et sa première classe.
--
-- L'INSERTION D'UN ÉLÈVE reste bornée à l'école et non à la direction,
-- volontairement : un élève qu'on vient de créer n'est inscrit dans
-- aucune classe, donc il n'a encore aucune direction à comparer. La
-- vraie porte est `student_class_enrollments`, déjà cloisonnée.
--
-- LA SUPPRESSION garde le directeur général en recours, pour les élèves
-- et les classes rattachés à aucune direction. Bornée aux seuls
-- directeurs, plus personne n'aurait pu les supprimer.
--
-- FRANCO-ARABE : RIEN N'EST RECLOISONNÉ. La filière NOMME la
-- responsabilité et ne restreint aucun périmètre RLS — décision de
-- `franco-arabe.sql`, laissée intacte. Les deux directeurs partagent la
-- même direction, donc le dossier de l'élève (effectif, frais, absences)
-- reste entier. Ajouter la filière aux bornes de `students` l'aurait
-- coupé en deux, ce qui est exactement ce qu'il ne faut pas.


-- ---------------------------------------------------------------------
-- TÂCHE 3 — « QUI NOTE » : LE DIRECTEUR DÉCIDE
-- ---------------------------------------------------------------------
--
-- `classes.notes_saisies_par` vaut « enseignant » (défaut) ou
-- « directeur ». Porté par la CLASSE et non par l'école : une même
-- école fait souvent les deux — saisie directe au second cycle, recopie
-- par la direction au premier, où l'enseignant rend une feuille.
--
-- LE RÉGLAGE DÉPLACE LE DROIT, IL NE L'AJOUTE PAS. Si la classe dit
-- « directeur », l'enseignant affecté NE PEUT PLUS noter. C'est tout
-- l'intérêt : un réglage qui n'aurait fait qu'ouvrir une porte de plus
-- ne changerait rien pour l'enseignant, et ne servirait donc à rien.
--
-- Une seule porte, `private.peut_noter_classe()`, à laquelle les trois
-- policies de `grades` s'adossent. Elles ne nomment plus l'encadrement
-- en bloc : un directeur général n'a pas à saisir une note, et un
-- directeur ne le fait que sur les classes qu'il a réglées ainsi.


-- ---------------------------------------------------------------------
-- TÂCHE 4 — SURVEILLANCE PAR CYCLE, ET SURVEILLANT GÉNÉRAL
-- ---------------------------------------------------------------------
--
-- « Vie scolaire » devient « Surveillance », à l'écran comme dans la
-- permission (`surveillance.tenir`).
--
-- `profiles.cycle` rattache un surveillant à UN cycle. Le surveillant
-- GÉNÉRAL, rôle nouveau, voit les trois : il n'a donc pas de cycle, et
-- lui en donner un le rétrécirait.
--
-- UN SURVEILLANT SANS CYCLE NE SURVEILLE RIEN, délibérément. Mieux vaut
-- une page vide, qui pousse à renseigner le rattachement, qu'un accès
-- silencieux à toute l'école — le défaut permissif est celui qu'on ne
-- découvre jamais.
--
-- LE CYCLE D'UNE CLASSE SE REPLIE SUR SA DIRECTION. `classes.cycle` est
-- un texte posé à la création, souvent oublié. Depuis que les directions
-- portent un cycle (tâche 2), `cycle_de_la_classe()` s'y replie : une
-- classe rattachée à une direction de premier cycle EST du premier
-- cycle, même si sa propre colonne est vide. Sans ce repli, un
-- surveillant ne verrait rien d'un effectif pourtant bien organisé.
--
-- L'ENSEIGNANT PERD L'ÉCRITURE sur les retenues et les violations : sa
-- vue de surveillance est en LECTURE, bornée à ses propres élèves.
-- Poser une sanction est un acte de la surveillance, pas de
-- l'enseignement. La capacité change de main — surveillant et directeur
-- la gardent — elle ne disparaît pas.
--
-- CE QUI N'EST PAS CLOISONNÉ PAR CYCLE, ET POURQUOI : les thèmes au rang
-- (`lineup_themes`) et les rappels du jour (`daily_reminders`) sont des
-- annonces d'établissement. Elles n'ont pas de cycle auquel se
-- rattacher, et leur en inventer un dépasserait la demande. Elles
-- restent donc communes à l'école.


-- ---------------------------------------------------------------------
-- TÂCHE 5 — LE COMPTABLE RESSERRÉ
-- ---------------------------------------------------------------------
--
-- Comptabilité, Classes, liste des Élèves. Rien d'autre.
--
-- AUCUNE POLICY N'A CHANGÉ ICI, et c'est le point : le RLS lui donnait
-- déjà exactement ces lectures — classes, élèves, inscriptions, frais,
-- paiements, paie, pointages, fiches enseignants pour la paie — et
-- AUCUNE donnée pédagogique : ni note, ni évaluation, ni présence. Le
-- resserrement était un problème de MENU, pas de sécurité. Vérifié
-- table par table avant de toucher quoi que ce soit.
--
-- Classes et Élèves ne sont pas un agrément : sans eux, il ne peut
-- rattacher ni un frais ni un paiement à qui que ce soit. Il les LIT
-- sans les écrire — inscrire un élève appartient à son directeur, créer
-- une classe aussi. Les écrans masquent donc leurs formulaires de
-- création, que le RLS refusait déjà.
--
-- Les STATISTIQUES lui sont retirées, bien qu'elles ne portent que des
-- agrégats : « rien d'autre » veut dire rien d'autre. Le tableau de bord
-- lui reste — c'est la page d'accueil, la retirer le laisserait sans
-- point d'entrée.


-- =====================================================================
-- VÉRIFIÉ, PAS SUPPOSÉ (2026-08-02)
-- =====================================================================
-- Sous de vraies réclamations JWT de promoteur :
--   lire les élèves ................................ passe
--   créer une classe ............................... refusé
--   créer une matière .............................. refusé
--   inscrire un élève .............................. refusé
--   ouvrir une année scolaire ...................... refusé
--   modifier une classe ............................ refusé (0 ligne)
--
-- Après reventilation :
--   policies citant is_admin ....................... 0
--   fonctions citant 'admin' ....................... 0
--   profils portant le rôle admin .................. 0
--   policies d'écriture citant le promoteur ........ 0
--
-- Sous de vraies réclamations JWT d'un directeur de la direction A,
-- avec une direction B voisine (données réelles, transaction annulée) :
--   classes visibles ................. 1 sur 2
--   enseignants visibles ............. 1 sur 2
--   créneaux de la direction B ....... 0
--   modifier la classe d'à côté ...... refusé (0 ligne)
--   modifier sa propre classe ........ 1 ligne
--   modifier l'enseignant d'à côté ... refusé (0 ligne)
--   modifier son enseignant .......... 1 ligne
--
-- « Qui note », le tableau de vérité complet, sous de vraies
-- réclamations JWT (données réelles, transaction annulée) :
--   réglage « enseignant » / l'enseignant note ..... passe
--   réglage « enseignant » / le directeur note ..... refusé
--   réglage « directeur »  / l'enseignant note ..... refusé
--   réglage « directeur »  / le directeur note ..... passe
--
-- Surveillance, sous de vraies réclamations JWT (classe du premier
-- cycle SANS cycle propre, rattachée à une direction de premier cycle,
-- pour éprouver le repli) :
--   surveillant du 1er cycle : classes visibles ...... 1 sur 2
--   surveillant du 1er cycle : poser une retenue ..... passe
--   surveillant général : classes visibles ........... 2 sur 2
--   enseignant : lit la retenue de son élève ......... 1
--   enseignant : poser une retenue ................... refusé
--   enseignant : constater une violation ............. refusé
